steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: [
      'build',
      '--build-arg', 'VITE_API_URL=${_VITE_API_URL}',
      '--build-arg', 'VITE_RAZORPAY_KEY_ID=${_VITE_RAZORPAY_KEY_ID}',
      '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}',
      '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/dhoond-repo/frontend',
      '.'
    ]
    
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/dhoond-repo/frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dhoond-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/dhoond-repo/frontend'
      - '--region'
      - 'us-central1'

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/dhoond-repo/frontend'

substitutions:
  _VITE_API_URL: "https://dhoond-backend-684217984422.us-central1.run.app"
  _VITE_GOOGLE_MAPS_API_KEY: "AIzaSyC6nuFdlL4et1PlQSyuiBosaV4rcWOaesM"
  _VITE_RAZORPAY_KEY_ID: "rzp_live_SeSxsY1JZab5Lw"

options:
  logging: CLOUD_LOGGING_ONLY
